Sat Apr 04 01:54:04 BRT 2015 : Apache Derby Servidor de Rede - 10.10.2.0 - (1582446) iniciado e pronto para aceitar conex칫es na porta 1527 em {3}
----------------------------------------------------------------
Sat Apr 04 01:54:05 BRT 2015:
 Inicializando o Derby vers칚o The Apache Software Foundation - Apache Derby - 10.10.2.0 - (1582446): inst칙ncia a816c00e-014c-82c7-5473-ffffa55b59ee
no diret칩rio de banco de dados /Users/humbertojuliao/facul/LP2Mack/DBCorretoAgoraVai/SistemaDaoCinema 

java.vendor=Oracle Corporation
java.runtime.version=1.8.0_40-b27
user.dir=/Applications/NetBeans/glassfish-4.1/javadb
os.name=Mac OS X
os.arch=x86_64
os.version=10.10.2
derby.system.home=/Users/humbertojuliao/facul/LP2Mack/DBCorretoAgoraVai
Carregador de classe do banco de dados iniciado - derby.database.classpath=''
Sat Apr 04 01:54:06 BRT 2015 Thread[DRDAConnThread_2,5,main] (XID = 1777), (SESSIONID = 0), (DATABASE = SistemaDaoCinema), (DRDAID = {1}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Ocorreu uma falha de autentica칞칚o da conex칚o.  Motivo: Autentica칞칚o inv치lida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: java.sql.SQLException: Ocorreu uma falha de autentica칞칚o da conex칚o.  Motivo: Autentica칞칚o inv치lida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Ocorreu uma falha de autentica칞칚o da conex칚o.  Motivo: Autentica칞칚o inv치lida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Sat Apr 04 01:54:06 BRT 2015 Thread[DRDAConnThread_2,5,main] (DATABASE = SistemaDaoCinema), (DRDAID = {1}), Ocorreu uma falha de autentica칞칚o da conex칚o.  Motivo: Autentica칞칚o inv치lida..
----------------------------------------------------------------
Sat Apr 04 01:55:43 BRT 2015: Shutting down Derby engine
----------------------------------------------------------------
Sat Apr 04 01:55:43 BRT 2015:
Encerrando a inst칙ncia a816c00e-014c-82c7-5473-ffffa55b59ee
----------------------------------------------------------------
<<<<<<< Updated upstream
Sat Apr 04 01:13:30 BRT 2015:
 Inicializando o Derby vers伋 The Apache Software Foundation - Apache Derby - 10.10.1.3 - (1557168): inst轟cia ed8940a7-014c-82a1-92d2-00005a934e19
no diret躁io de banco de dados C:\Users\DANIEL\Documents\GitHub\LP2Mack\DBCorretoAgoraVai\SistemaDaoCinema 

java.vendor=Oracle Corporation
java.runtime.version=1.8.0_11-b12
user.dir=C:\Program Files\Java\jdk1.8.0_11\db
os.name=Windows 8.1
os.arch=amd64
os.version=6.3
derby.system.home=C:\Users\DANIEL\Documents\GitHub\LP2Mack\DBCorretoAgoraVai
Carregador de classe do banco de dados iniciado - derby.database.classpath=''
----------------------------------------------------------------
Sat Apr 04 02:05:52 BRT 2015: Shutting down Derby engine
=======
>>>>>>> Stashed changes
